name: Push to DockerHub
on: [push]

jobs:
  build-vue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file client/Dockerfile --tag abdoubentegar/vue-enventory
      - name: login
        run: |
          echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: push to docker hub
        run: |
          docker push abdoubentegar/vue-enventory

  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file server/Dockerfile --tag abdoubentegar/enventory-api
      - name: login
        run: |
          echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: push to docker hub
        run: |
          docker push abdoubentegar/enventory-api
